### ISSUE TITLE
[Bug] Tables

### ISSUE THREAD

**Issue by osahene** [creativetimofficial/vue-notus#3]
### Version
latest version
### Reproduction link
https://codepen.io/osahene/pen/zYBKJQg
### Operating System
Windows 10
### Device
msi-7586
### Browser & Version
firefox 81.0.2 (64-bit)
### Steps to reproduce
none
### What is expected?
I need only one table. Any help?
### What is actually happening?
At the section of the table, two tables appear. https://demos.creative-tim.com/vue-notus/?_ga=2.166260151.840469472.1603144735-2105352621.1601920829#/admin/tables

---

**Comment by EINazare** [comment]
Hello there, @osahene ,

Thank you for your interest in working with our products.
We do not understand your issue. Please detail, otherwise, we'll close it.

Best,
Manu

**Comment by osahene** [comment]
I have been able to resolve it. Thank you.
